map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "cj_dongtan.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False
